package com.example.s152780_lykkehjulet.Files

val Honorable_Mentions : List<String> =
    listOf(
        "Per Mikkelsen",
        "Mikkel Persen",
        "Gabe Newell",
        "Jørgen Jensen",
        "Jens Jørgensen",
        "Mark ZuckerBerg",
        "Elon Musk",
        "Bill Gates",
        "Per Mikkelsen",
        "Mikkel Persen",
        "Gabe Newell",
        "Jørgen Jensen",
        "Jens Jørgensen",
        "Mark ZuckerBerg",
        "Elon Musk",
        "Bill Gates",
        "Per Mikkelsen",
        "Mikkel Persen",
        "Gabe Newell",
        "Jørgen Jensen",
        "Jens Jørgensen",
        "Mark ZuckerBerg",
        "Elon Musk",
        "Bill Gates",
        "Per Mikkelsen",
        "Mikkel Persen",
        "Gabe Newell",
        "Jørgen Jensen",
        "Jens Jørgensen",
        "Mark ZuckerBerg",
        "Elon Musk",
        "Bill Gates",
        "Per Mikkelsen",
        "Mikkel Persen",
        "Gabe Newell",
        "Jørgen Jensen",
        "Jens Jørgensen",
        "Mark ZuckerBerg",
        "Elon Musk",
        "Bill Gates"
    )

